"""Add DPIA basic data fields

Revision ID: 91e491d070fa
Revises: fc98beb32d4e
Create Date: 2026-08-25 08:25:21.796391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e491d070fa'
down_revision = 'fc98beb32d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpia_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_manager', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('department_function_agency', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('area_ministry', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('region', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nature_of_change', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('other_nature_of_change', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('implementation_timescales', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpia_assessments', schema=None) as batch_op:
        batch_op.drop_column('implementation_timescales')
        batch_op.drop_column('other_nature_of_change')
        batch_op.drop_column('nature_of_change')
        batch_op.drop_column('region')
        batch_op.drop_column('area_ministry')
        batch_op.drop_column('department_function_agency')
        batch_op.drop_column('project_manager')

    # ### end Alembic commands ###
