"""add assigned_dpo_id

Revision ID: a9923b7413dd
Revises: a5651d8f3e4f
Create Date: 2026-09-08 09:26:42.827737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9923b7413dd'
down_revision = 'a5651d8f3e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpia_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_dpo_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['assigned_dpo_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpia_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_dpo_id')

    # ### end Alembic commands ###
