"""Add DPS review fields

Revision ID: e95708740909
Revises: 91e491d070fa
Create Date: 2026-08-25 09:07:57.259950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e95708740909'
down_revision = '91e491d070fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpia_assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dps_review_decision', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dps_review_comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dps_reviewed_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('dps_reviewed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['dps_reviewed_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dpia_assessments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('dps_reviewed_at')
        batch_op.drop_column('dps_reviewed_by')
        batch_op.drop_column('dps_review_comment')
        batch_op.drop_column('dps_review_decision')

    # ### end Alembic commands ###
