"""Create DPIA screening table

Revision ID: fc98beb32d4e
Revises: 54b84c471995
Create Date: 2026-08-25 08:05:11.150498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc98beb32d4e'
down_revision = '54b84c471995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dpia_screenings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('involves_personal_data', sa.Boolean(), nullable=True),
    sa.Column('personal_data_subject_types', sa.JSON(), nullable=True),
    sa.Column('personal_data_categories', sa.JSON(), nullable=True),
    sa.Column('sensitive_personal_data_categories', sa.JSON(), nullable=True),
    sa.Column('other_personal_data', sa.Text(), nullable=True),
    sa.Column('data_subject_locations', sa.JSON(), nullable=True),
    sa.Column('data_subject_specific_countries', sa.Text(), nullable=True),
    sa.Column('approximate_users_with_access', sa.Integer(), nullable=True),
    sa.Column('approximate_records_per_year', sa.Integer(), nullable=True),
    sa.Column('system_use_locations', sa.JSON(), nullable=True),
    sa.Column('system_use_specific_countries', sa.Text(), nullable=True),
    sa.Column('system_hosting_locations', sa.JSON(), nullable=True),
    sa.Column('system_hosting_specific_countries', sa.Text(), nullable=True),
    sa.Column('system_host', sa.String(length=255), nullable=True),
    sa.Column('system_support_types', sa.JSON(), nullable=True),
    sa.Column('support_locations', sa.JSON(), nullable=True),
    sa.Column('support_specific_countries', sa.Text(), nullable=True),
    sa.Column('third_party_access', sa.Boolean(), nullable=True),
    sa.Column('third_party_access_explanation', sa.Text(), nullable=True),
    sa.Column('risk_tier', sa.String(length=50), nullable=True),
    sa.Column('full_pia_required', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['dpia_assessments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dpia_screenings')
    # ### end Alembic commands ###
